apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
    version: v1
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:v1
        name: result
        ports:
        - containerPort: 80
          name: result
