apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
    version: v1
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - image: kodekloud/examplevotingapp_worker:v1
          name: worker
