apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
    service: db
  name: db
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: db
