apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
    service: result
  name: result
  namespace: vote
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: result
