apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
    service: vote
  name: vote
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: vote
