apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: db
        version: v1      
    spec:
      serviceAccountName: db
      containers:
      - name: postgres
        image: postgres:9.4
        imagePullPolicy: IfNotPresent 
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
