apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: redis
        version: v1      
    spec:
      serviceAccountName: redis
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
        - name: redis-data
          emptyDir: {}
