apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
    version: v1  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: result
        version: v1      
    spec:
      serviceAccountName: result
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:v1
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
          name: result
