apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: vote
        version: v1      
    spec:
      serviceAccountName: vote
      containers:
      - name: vote
        image: kodekloud/examplevotingapp_vote:v1   
        imagePullPolicy: IfNotPresent     
        ports:
        - containerPort: 80
          name: vote
