apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: worker
        version: v1      
    spec:
      serviceAccountName: worker
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker:v1
        imagePullPolicy: IfNotPresent
